PV1-157 :: Implemented path optimization
mindera-gaming/svg-parser pull request #3
Opened 2021-04-16 10:15 UTC by Goncalo-Marques

## Issue(s)

 - https://mindera.atlassian.net/browse/PV1-157?atlOrigin=eyJpIjoiNmQ3MGNmM2FmZGM2NDM5Y2I0ZTMxMWFjNTE2NGMzMWEiLCJwIjoiaiJ9

## Description

- Optimise paths by removing unnecessary paths

Removed/updated:
 - Internal "Point" structure and start using points from the 'go-math' module

## Depends on

 - #2 
 -  https://github.com/mindera-gaming/go-math/pull/4

2021-04-19 15:53 UTC, GambuzX requested changes
Looks good overall, just a few considerations

2021-04-19 15:53 UTC, GambuzX commented on svg/path.go
> +			middle := vector2.Point{
Not sure if this can be done to the control points. Did you test if this resulted in the curve you want?

2021-04-19 15:53 UTC, GambuzX commented on svg/path.go
> +			if math.IsInf(slope, 1) {
Probably should check `math.IsInf` before the subtraction and calling `math.Abs` no?
Not sure how this will behave when the slope returns Infinite

2021-04-19 15:53 UTC, GambuzX commented on svg/path.go
> +func optimizePaths(paths []PathData, slopeTolerance float64) (optimizedPaths []PathData) {
Is it guaranteed that the paths to be merged will be in sequence?

2021-04-20 09:36 UTC, Goncalo-Marques commented on svg/path.go
> +			middle := vector2.Point{
I was reviewing the code and noticed that the control points are being calculated differently in each command.
Maybe this optimization should be done, in each parse of a command, before creating the paths.
What do you think?

2021-04-20 09:38 UTC, Goncalo-Marques commented on svg/path.go
> +			if math.IsInf(slope, 1) {
Yes, you are right

2021-04-20 10:28 UTC, Goncalo-Marques commented on svg/path.go
> +func optimizePaths(paths []PathData, slopeTolerance float64) (optimizedPaths []PathData) {
Given the tests I did, they appeared to be sequential

2021-04-20 10:35 UTC, Goncalo-Marques commented on svg/path.go
> +			}
https://github.com/mindera-gaming/svg-parser/pull/3#discussion_r615968817
@GambuzX, Was this what you had in mind?

2021-04-20 11:56 UTC, GambuzX requested changes

2021-04-20 11:56 UTC, GambuzX commented on svg/path.go
> +			}
I think it just has the problem that slope becomes 0 if this `if` condition is true

2021-04-20 11:56 UTC, GambuzX commented on svg/path.go
> +			if slope < slopeTolerance {
If `slope` is 0 because of having Inf values above, won't this always be true?

2021-04-20 11:56 UTC, GambuzX commented on svg/path.go
> +			}
I would separate this in variables that would allows to check every case, like so:

```go
slope1 := paths[i].Start.Slope(paths[i].End)
slope2 := paths[j].Start.Slope(paths[j].End)

if IsInf(slope1) && IsInf(slope2) {
    slope = 0
}
if IsInf(slope1) && !IsInf(slope2) {
    slope = Inf
}
...
```

2021-04-20 11:56 UTC, GambuzX commented on svg/path.go
> +			}
Alternatively, I have a feeling that this might be easier to do with polar coordinates. But I'm not that familiar with them anymore 😅

2021-04-20 11:56 UTC, GambuzX commented on svg/path.go
> +			middle := vector2.Point{
I'm not really familiar with that part of the commands, so I don't know what you are talking about 🙃 
But can you optimize the control points before even creating the paths?

2021-04-20 13:26 UTC, Goncalo-Marques commented on svg/path.go
> +			middle := vector2.Point{
Yes, I think I can do that

2021-04-20 13:30 UTC, GambuzX commented on svg/path.go
> +			middle := vector2.Point{
I was just asking if that was feasible, not saying that I think it would be better to do so 😅

2021-04-20 13:30 UTC, GambuzX commented on svg/path.go
> +			middle := vector2.Point{
I really am not familiar with this part, so I will leave it up to you

2021-04-20 13:43 UTC, Goncalo-Marques commented on svg/path.go
> +			middle := vector2.Point{
I think I should do that 😄
Otherwise, in the future, we won't be able to support curves and that's a problem :/

2021-04-20 14:20 UTC, Goncalo-Marques commented on svg/path.go
> +			}
I found this video that explains the relationship between polar and Cartesian coordinates:
- https://youtu.be/vpl9lZTyznU?t=414 (portuguese only)

What do you think about changing the current approach?

2021-04-21 15:41 UTC, GambuzX commented on svg/path.go
>  			}
What if the initialPathSlope is not Inf, but the lastPathSlope is ?
Does this need a special case or the math.Abs calculation returns Inf ?

2021-04-21 22:14 UTC, Goncalo-Marques commented on svg/path.go
>  			}
I could be wrong, but I don't think this case needs special treatment:
- https://play.golang.org/p/wTPDn3zYUAA

2021-04-22 15:18 UTC, GambuzX commented on svg/path.go
> +func parseAbscissa(x, command string) (float64, error) {
Wouldn't it be clearer to create methods "parseX" and "parseY"?
I leave it up to you tho, either way is fine

2021-04-22 15:18 UTC, GambuzX commented on svg/path.go
> +func optimizePoints(previousPoint vector2.Point, lastPoint vector2.Point, currentIndex int, command string, options parserOptions) (int, error) {
I'm a bit confused with what each point represents: previousPoint, lastPoint, currentPoint, optimisedPoint

2021-04-22 15:18 UTC, GambuzX commented on svg/path.go
> +	currentPoint.Add(tempPoint)
Why do you need to Add this to the currentPoint?

2021-04-22 16:10 UTC, Goncalo-Marques commented on svg/path.go
> +	currentPoint.Add(tempPoint)
It is because the `currentPoint ` can be relative to the `tempPoint` (`lastPoint`)

2021-04-22 21:57 UTC, Goncalo-Marques commented on svg/path.go
> +func optimizePoints(previousPoint vector2.Point, lastPoint vector2.Point, currentIndex int, command string, options parserOptions) (int, error) {
How do you think I could make that more perceptible in the code?

---

**lastPoint:** This is the last point on the previous path
**previousPoint:** This is the point before the current one
**currentIndex:** This is the index of the current point being "tested" (whether or not it can be skipped)
**optimisedPoint:** This is the point that comes after the `currentPoint (currentIndex)` to check whether or not it is possible to override it (`currentPoint`). If it is possible to skip the `currentPoint`, the `currentPoint` becomes the `optimisedPoint`

_Tell me if this has made you more confused than before :P_

2021-04-26 17:44 UTC, GambuzX commented on svg/path.go
> +		tempPoint = lastPoint
Why not use the tempPoint from line 455?

2021-04-26 17:46 UTC, GambuzX commented on svg/path.go
> +	currentPoint.Add(tempPoint)
So the coordinates in indexes (i, i+1) in options.Data are relative to the ones in (i-2, i-1) ?

2021-04-26 22:27 UTC, Goncalo-Marques commented on svg/path.go
> +	currentPoint.X += tempPoint.X
That was the problem to have done this last update.
`.Add()` returns the addition calculation between two points, but does not update them

2021-04-26 22:32 UTC, Goncalo-Marques commented on svg/path.go
> +func optimizePoints(previousPoint vector2.Point, lastPoint vector2.Point, currentIndex int, command string, options parserOptions) (int, error) {
This is because `lastPoint` is the last point coming from the parse of the last SVG path. 
Meanwhile, `previousPoint` is the last point of the SVG path that is currently being parsed.

2021-04-26 22:51 UTC, Goncalo-Marques commented on svg/path.go
> +		tempPoint = lastPoint
Sorry, that is a leftover

2021-04-26 23:14 UTC, Goncalo-Marques commented on svg/path.go
> +	currentPoint.Add(tempPoint)
Not really... 
Here, the `lastPoint` is the last point that comes from the parse of the last SVG path.
What you are saying corresponds to the `previousPoint`.

2021-04-27 16:40 UTC, GambuzX commented on svg/path.go
> +	currentPoint.X += tempPoint.X
I see. I think you could define Add() with a pointer receiver to fix that, but this is good as well

2021-04-27 16:43 UTC, GambuzX commented on svg/path.go
> +func optimizePoints(previousPoint vector2.Point, lastPoint vector2.Point, currentIndex int, command string, options parserOptions) (int, error) {
Alright, I think I get it. Before accepting, can you just add this info about what means what in the code? 
If you don't think its necessary just say so, but since it was a bit confusing to me at first

2021-07-07 07:52 UTC, merged